# Render.com Blueprint для BetonApp
# Автоматическое развертывание полного приложения

services:
  # Backend API Service
  - type: web
    name: betonapp-backend
    env: node
    plan: starter
    rootDir: ./backend
    buildCommand: |
      npm ci
      npm run build
      npx prisma generate
      npx prisma migrate deploy
      npm run prisma:seed:prod
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: betonapp-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: "info"

  # Frontend Static Site
  - type: web
    name: betonapp-frontend
    env: static
    plan: starter
    rootDir: ./frontend
    buildCommand: |
      npm ci
      npm run build:prod
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      - path: /sw.js
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://betonapp-backend.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_APP_TITLE
        value: "BetonApp"
      - key: VITE_APP_VERSION
        value: "1.0.0"
      - key: VITE_APP_ENVIRONMENT
        value: "production"
      - key: VITE_API_BASE_URL
        value: "https://betonapp-backend.onrender.com"
      - key: VITE_API_TIMEOUT
        value: "30000"
      - key: VITE_ENABLE_DEBUG
        value: "false"
      - key: VITE_ENABLE_CONSOLE_LOGS
        value: "false"
      - key: VITE_ENABLE_TEST_DATA
        value: "false"

databases:
  - name: betonapp-database
    databaseName: betonapp_production
    user: betonapp_user
    plan: starter